demo_request:
  email: shwetanagapure1024@gmail.com
  subject: "New Demo Request"

pricing_inquiry:
  email: shuhaib.7073@gmail.com
  subject: "Pricing Inquiry Lead"

job_application_process:
  email: hr@company.com
  subject: "New Job Application"

internship_opportunities:
  email: internship@company.com
  subject: "Internship Interest"

technical_support_contact:
  email: support@company.com
  subject: "Support Request"
